name: Test & Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonare repository
        uses: actions/checkout@v3

      - name: Setare Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalare dependințe
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rulare teste cu pytest
        run: |
          pytest
